# Generated by Django 5.1.8 on 2025-04-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('indicador', models.CharField(max_length=100, unique=True)),
                ('formula_calculo', models.CharField(max_length=100, unique=True)),
                ('medio_verificador', models.CharField(max_length=100, unique=True)),
                ('tipo_medida', models.CharField(max_length=100, unique=True)),
                ('frecuencia', models.CharField(choices=[('unica', 'Única'), ('anual', 'Anual'), ('cada_5_anios', 'Cada 5 años')], default='unica', max_length=20)),
            ],
            options={
                'db_table': 'medida',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad', models.CharField(choices=[('cantidad', 'cantidad'), ('porcentaje', 'Porcentaje')], default='cantidad', max_length=20)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='app_ppda.medida')),
            ],
            options={
                'db_table': 'indicador',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('grupo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'organismo',
            },
        ),
        migrations.AddField(
            model_name='medida',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organismo', to='app_ppda.organismo'),
        ),
        migrations.CreateModel(
            name='Ppda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comunas', models.ManyToManyField(blank=True, related_name='comunas', to='app_ppda.comuna')),
            ],
            options={
                'db_table': 'ppda',
            },
        ),
        migrations.CreateModel(
            name='PpdaMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ppda.medida')),
                ('ppda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ppda.ppda')),
            ],
            options={
                'db_table': 'ppda_medidas',
                'unique_together': {('ppda', 'medida')},
            },
        ),
        migrations.AddField(
            model_name='ppda',
            name='medidas',
            field=models.ManyToManyField(blank=True, related_name='medidas', through='app_ppda.PpdaMedida', to='app_ppda.medida'),
        ),
        migrations.CreateModel(
            name='PpdaOrganismos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ppda.organismo')),
                ('ppda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ppda.ppda')),
            ],
            options={
                'db_table': 'ppda_organismos',
                'unique_together': {('ppda', 'organismo')},
            },
        ),
        migrations.AddField(
            model_name='ppda',
            name='organismos',
            field=models.ManyToManyField(blank=True, related_name='organismos', through='app_ppda.PpdaOrganismos', to='app_ppda.organismo'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app_ppda.indicador')),
                ('ppda_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app_ppda.ppdamedida')),
            ],
            options={
                'db_table': 'registro',
                'unique_together': {('ppda_medida', 'indicador', 'fecha')},
            },
        ),
    ]
