# Generated by Django 5.1.6 on 2025-02-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ppda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('ppdas', models.ManyToManyField(blank=True, related_name='comunas', to='app_ppda.ppda')),
            ],
        ),
    ]
