# Generated by Django 5.1.6 on 2025-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ppda', '0002_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('indicador', models.CharField(max_length=100, unique=True)),
                ('formula_calculo', models.CharField(max_length=100, unique=True)),
                ('medio_verificador', models.CharField(max_length=100, unique=True)),
                ('tipo_medida', models.CharField(max_length=100, unique=True)),
                ('frecuencia', models.CharField(choices=[('unica', 'Única'), ('anual', 'Anual'), ('cada_5_anios', 'Cada 5 años')], default='unica', max_length=20)),
            ],
        ),
    ]
