# Generated by Django 5.1.6 on 2025-02-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ppda', '0003_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='ppdas',
        ),
        migrations.AddField(
            model_name='ppda',
            name='comunas',
            field=models.ManyToManyField(blank=True, related_name='comunas', to='app_ppda.comuna'),
        ),
    ]
