# Generated by Django 5.1.6 on 2025-02-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ppda', '0004_remove_comuna_ppdas_ppda_comunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppda',
            name='medidas',
            field=models.ManyToManyField(blank=True, related_name='medidas', to='app_ppda.medida'),
        ),
    ]
